### ISSUE TITLE
synthetic data not generated for the following config

### ISSUE THREAD

**Issue by shahbaz-ali** [Cloud-Innovation-Partners/cloudtdms#5]
synthetic data generation fails for the `configuration`:
```python
"schema": [
        {"field_name": "fname", "type": "personal.first_name", "locale": "fa_IR"},
        {"field_name": "lname", "type": "personal.last_name",},
        {"field_name": "sex", "type": "personal.gender"},
        {"field_name": "email", "type": "personal.email_address"},
        {"field_name": "user", "type": "personal.username"},
        {"field_name": "univ", "type": "personal.university"},
        {"field_name": "lang", "type": "personal.language"},
        {"field_name": "norm", "type": "statistics.normal"},
        {"field_name": "exp", "type": "statistics.exponential"},
        {"field_name": "com", "type": "company.company_name", "locale":"en_GB"},
        {"field_name": "auto_increment", "type": "basics.auto_increment",'prefix':'INC','suffix':'PR'},
        {"field_name": "number_range", "type": "basics.number_range",'start':300,'end':400},
        {"field_name": "boolean", "type": "basics.boolean",'set_val':'yes,no'},
        {"field_name": "frequency", "type": "basics.frequency"},
        {"field_name": "color", "type": "basics.color",'format':'hex-code'},
        {"field_name": "country", "type": "location.country"},
        {"field_name": "country121", "type": "location.country"},
        {"field_name": "city", "type": "location.city"},
        {"field_name": "latitude", "type": "location.latitude"},
        {"field_name": "longitude121", "type": "location.address"},
        {"field_name": "longitude34", "type": "location.address"},
        {"field_name": "phone121", "type": "location.phone_number",'format':'#-(###)-###-####'},
        {"field_name": "phone34", "type": "location.phone_number",'format':'#-(###)-###-####'},
        {"field_name": "muncipality", "type": "location.municipality"},
        {"field_name": "airport", "type": "location.airport"}

    ],
```

with following error

```
[2020-09-14 06:06:27,899] {taskinstance.py:1150} ERROR - Length of values (101) does not match length of index (100)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/cloudtdms/system/dags/my_synthetic_data.py", line 81, in data_generator
    _all(data_frame, nrows, args_array)
  File "/opt/cloudtdms/system/cloudtdms/providers/basics/__init__.py", line 56, in basics
    number_range(data_frame, number, field_names.get('number_range'))
  File "/opt/cloudtdms/system/cloudtdms/providers/basics/__init__.py", line 347, in number_range
    data_frame[data_frame_col_name] = range_list
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 3040, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 3116, in _set_item
    value = self._sanitize_column(key, value)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 3763, in _sanitize_column
    value = sanitize_index(value, self.index)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 748, in sanitize_index
    "Length of values "
ValueError: Length of values (101) does not match length of index (100)
```

**Comment by shahbaz-ali** [comment]
@md-akeel 

It seems the `number_range()` generator function needs refactoring and handling of above case
please re-visit the following code 

```
range_list_len = len(range_list)
        if range_list_len < number:
            diff = number - range_list_len
            range_list = range_list * diff
            range_list = range_list[:number]

        data_frame[data_frame_col_name] = range_list
```
